config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'families/new'

  get 'home/index'
  root 'home#index'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :families, :only => [:show, :new, :create, :index]
  resources :users do
    resources :accounts
    resources :incomes
    resources :expenses
  end
  
  resources :categories
  resources :suppliera
  

end

app/models/family.rb
# == Schema Information
#
# Table name: families
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  pass       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Family < ActiveRecord::Base
	has_many :users
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController

  def index
    @families = Family.all
  end

  def new
    logger.debug "Hello"
  end

  def create
    logger.debug family_params
    @families = Family.new(family_params)
    
    logger.debug @families.inspect
    if @families.save
      
      flash[:families_id] = @families.id
      redirect_to families_url
    else
      render :action => "new"
    end
  end

  private

  def family_params
    params.require(:families).permit(:name, :pass)
  end
end

app/helpers/families_helper.rb
module FamiliesHelper
  def family_accounts family
    family = Family.find(family)
    family_accounts = []

    family.users.each do |u|
      family_accounts += u.accounts
    end
  end
end

app/views/families/index.html.erb
<h1>That are all your families</h1>

<%= @families.each do |t| %>
   <%= puts t.inspect %> </ br>
<% end %>

app/views/families/new.html.erb
<h1>Families#new</h1>

<%= form_for :families, url: families_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :pass, "Password" %><br>
    <%= f.password_field :pass %>
  </p>


  <p>
    <%= f.label :confirm_password %><br>
    <%= f.password_field :confirm_password %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>