config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'families/new'

  get 'home/index'
  root 'home#index'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :families, :only => [:show, :new, :create, :index]
  resources :users do
    resources :accounts
    resources :incomes
    resources :expenses
  end
  
  resources :categories
  resources :suppliera
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  password   :string(255)      not null
#  family_id  :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  email      :string(255)
#

class User < ActiveRecord::Base
  belongs_to :family
  has_many :accounts
  has_many :incomes
  has_many :expenses
 
  validates :name, :password_digest, :family_id, :email, presence: true
  validate  :email, uniqueness: true
  
  has_secure_password # adds password security :
#The ability to save a securely hashed password_digest attribute to the database
#A pair of virtual attributes18 (password and password_confirmation), including presence validations upon object creation and a validation requiring that they match
#An authenticate method that returns the user when the password is correct (and false otherwise)
  validates :password, presence: true, length: { minimum: 4 }
  validates :password, :confirmation => true
end

app/controllers/users_controller.rb
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  password   :string(255)      not null
#  family_id  :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  email      :string(255)

class UsersController < ApplicationController


  def index
    @users = User.all
  end

  def create
    logger.debug user_params
    logger.debug "Password #{params[:user]}"
    logger.debug "password_confirmation #{params[:password_confirmation]}"

    @user = User.new user_params
    logger.debug @user.inspect

    if @user.save
      logger.debug "success"
      redirect_to @user
    else
      flash[:error] = @user.errors.full_messages[0]
      redirect_to new_user_path
    end
  end

  def new
    
  end

  def edit
  end

  def show
    redirect_to root_path unless logged_in?
    @user = current_user
  end

  def update

  end

private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :email, :family_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<table id="users_table" class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Family</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
    <tr>
      <td><%= u.name %></td>
      <td><%= u.email %></td>
      <td><%= Family.find(u.family_id).name %></td>
    </tr>
    <% end %>
   </tbody>
</table>
<%= link_to 'User', controller: 'users' %>

app/views/users/new.html.erb
<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.label :family, "Select your family" %><br>
    <%= f.select :family_id, Family.all.collect { |c| [ c.name, c.id ] }, include_blank: true %>
    <%=link_to "Register a family", new_family_path %>
  </p>

  <p>
    <%= f.submit class: "btn btn-primary" %>
  </p>
<% end %>

app/views/users/show.html.erb
<section>
<h2>User Profile</h2>
	<ul>
	<li>  <%= gravatar_for @user %> </li>
	<li>Name: <%= @user.name %> </li>
	<li>E-Mail: <%= @user.email %> </li>
	</ul>
</section>