config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'families/new'

  get 'home/index'
  root 'home#index'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :families, :only => [:show, :new, :create, :index]
  resources :users do
    resources :accounts
    resources :incomes
    resources :expenses
  end
  
  resources :categories
  resources :suppliera
  

end

app/models/income.rb
# == Schema Information
#
# Table name: Incomes
#
#  id          :integer     not null, primary key
#  title       :string(255)
#  date        :date 
#  description :string(255)
#  income      :decimal
#  account_id  :integer
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Income < ActiveRecord::Base
  belongs_to :account # Will create FK account_id
  # has_one :user Will Create FK income_id in User model
  belongs_to :user
  
  validates :title, :date, :user_id, :account_id, :income, presence: true
  validates :income, numericality: true
  
end

app/controllers/incomes_controller.rb
require "pp"

class IncomesController < ApplicationController
  def index
  end

  def new
  end

  def create
    logger.debug "Parameters came from income create form #{income_params}"
    params = income_params.merge({user_id: current_user.id})
    pp params
    @income = Income.new(params)

    logger.debug "After income creation #{@income}"

    if @income.save
      logger.debug  [current_user, @income].inspect
      add_income_to_account @income.account_id, @income.income
      redirect_to [current_user, @income]
    else
      redirect_to new_user_income_path(current_user)
    end
  end

  def show
    @income = Income.find(params[:id])
  end

  private

  def income_params
    params.require(:income).permit(:title, :date, :description, :income, :account_id)
  end

  def add_income_to_account account_id, income
    account = Account.find(account_id)
    account.balance += income;
    account.save
  end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/index.html.erb
<h1>All <%= current_user.name.titleize %> incomes</h1>

<h2> Incomes number <%= current_user.incomes.length %> </h2>
<table class="table table-hover table-bordered">
<tbody>
  <tr>
    <th>Description</th>
    <th>Income Value</th>
    <th>To Account</th>
    <th>Date</th>
  </tr>
</tbody>
  <% current_user.incomes.each do |income| %>
    <tr onclick="window.location.href='<%= income.id %>'">
      <td><%= income.description %></td>
      <td><%= income.income %></td>
      <td><%= income.account.name %></td>
      <td><%= income.account.created_at %></td>
    </tr>
  <% end %>
  <%= link_to t("incomes.create_income_link"),  new_user_income_path(current_user) %>
</table>

app/views/incomes/new.html.erb
<div class="row">
  <div class="col-md-7 col-md-offset-2">
<%= form_for :income, :builder => JRForm , url: user_incomes_path do |f| %>
  <div class="form_group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>

    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", rows: 8 %>

    <%= f.label :income %>
    <%= f.monetary_field :income, 0.00, "form-control" %>

    <%= f.label :account, "Select account for the income" %>
    <%= f.select :account_id, current_user.accounts.all.collect { |a| [ a.name, a.id ] }, {}, 
                 include_blank: false, class: "form-control input-lg-2 input-sm" %>

    <%= f.label :date, "Select Date for the Income" %>
    <%= f.date_field :date, :value => Time.now.strftime('%Y-%m-%d'),  class: "form-control" %>

    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>
</div>

app/views/incomes/show.html.erb
<%= link_to 'Back', user_income_path %>

	<p>
	  <strong>Title:</strong>
	  <%= @income.description %>
	</p>
	 
	<p>
	  <strong>Text:</strong>
	  <%= @income.income %>
	</p>