config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'families/new'

  get 'home/index'
  root 'home#index'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :families, :only => [:show, :new, :create, :index]
  resources :users do
    resources :accounts
    resources :incomes
    resources :expenses
  end
  
  resources :categories
  resources :suppliera
  

end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  balance    :decimal(, )
#  user_id    :integer
#  icon       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Account < ActiveRecord::Base
  belongs_to  :user
  has_many    :incomes
  has_many    :expenses

  validates :name, :user_id, :balance, presence: true
  validates :balance, numericality: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :sub_categories, class: Category, foreign_key: :category_id
  has_and_belongs_to_many :suppliers
  belongs_to :parent_category, class: Category, foreign_key: :category_id
  
  has_attached_file :icon, styles: { medium: "100x100>", thumb: "50x50>" }
  validates_attachment_content_type :icon, content_type: /\Aimage\/.*\Z/
  
  validates :description, presence: true
end

app/models/expense.rb
#
# Table name: Expenses
#
#  id           :integer          not null, primary key
#  description  :string(255)
#  amount       :decimal
#  account_id   :integer
#  user_id      :integer
#  date         :date
#  created_at   :datetime
#  updated_at   :datetime
#


class Expense < ActiveRecord::Base
  belongs_to :account
  belongs_to :user
  
  validates :description, :user_id, :account_id, :amount, :date, presence: true
  validates :amount, numericality: true
end

app/models/family.rb
# == Schema Information
#
# Table name: families
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  pass       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Family < ActiveRecord::Base
	has_many :users
end

app/models/income.rb
# == Schema Information
#
# Table name: Incomes
#
#  id          :integer     not null, primary key
#  title       :string(255)
#  date        :date 
#  description :string(255)
#  income      :decimal
#  account_id  :integer
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Income < ActiveRecord::Base
  belongs_to :account # Will create FK account_id
  # has_one :user Will Create FK income_id in User model
  belongs_to :user
  
  validates :title, :date, :user_id, :account_id, :income, presence: true
  validates :income, numericality: true
  
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  has_and_belongs_to_many :categories
  
  validates :name, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  password   :string(255)      not null
#  family_id  :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  email      :string(255)
#

class User < ActiveRecord::Base
  belongs_to :family
  has_many :accounts
  has_many :incomes
  has_many :expenses
 
  validates :name, :password_digest, :family_id, :email, presence: true
  validate  :email, uniqueness: true
  
  has_secure_password # adds password security :
#The ability to save a securely hashed password_digest attribute to the database
#A pair of virtual attributes18 (password and password_confirmation), including presence validations upon object creation and a validation requiring that they match
#An authenticate method that returns the user when the password is correct (and false otherwise)
  validates :password, presence: true, length: { minimum: 4 }
  validates :password, :confirmation => true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  password   :string(255)      not null
#  family_id  :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  email      :string(255)

class UsersController < ApplicationController


  def index
    @users = User.all
  end

  def create
    logger.debug user_params
    logger.debug "Password #{params[:user]}"
    logger.debug "password_confirmation #{params[:password_confirmation]}"

    @user = User.new user_params
    logger.debug @user.inspect

    if @user.save
      logger.debug "success"
      redirect_to @user
    else
      flash[:error] = @user.errors.full_messages[0]
      redirect_to new_user_path
    end
  end

  def new
    
  end

  def edit
  end

  def show
    redirect_to root_path unless logged_in?
    @user = current_user
  end

  def update

  end

private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :email, :family_id)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def has_suppliers? cat
    !cat.suppliers.empty?
  end
  
  def has_sub_categories? cat
    !cat.sub_categories.empty?
  end
  
  def has_parent_category? cat
    !cat.parent_category.nil?
  end
  
  def all_parent_categories
    Category.where "category_id is null"
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
  def family_accounts family
    family = Family.find(family)
    family_accounts = []

    family.users.each do |u|
      family_accounts += u.accounts
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/jr_form.rb
class JRForm < ActionView::Helpers::FormBuilder
  def monetary_field(objname, value, classes)
    text_field "#{objname}", :value => ("%0.2f" % value), class: classes, :size => 6
  end
end 

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    #Checking for this requires the use of the “not” operator written using an exclamation point ! and usually read as “bang”.
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RachevFinance" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">RachevFinance</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
          <% if logged_in? %>
            <li><%= link_to t("nav_menu.home"),  	user_path(current_user) %></li>
            <li><%= link_to t("nav_menu.accounts"), user_accounts_path(current_user) %></li>
            <li><%= link_to t("nav_menu.income"), 	user_incomes_path(current_user)  %></li>
            <li><%= link_to t("nav_menu.expense"), 	user_expenses_path(current_user)  %></li>
            <li><%= link_to t("nav_menu.categories"), 	categories_path  %></li>
            <li><%= link_to t("nav_menu.budget"), 	"/path2"  %></li>
            <li><%= link_to t("nav_menu.analysis"), "/path2"  %></li>
          <% end %>
          </ul>
          <!--Right Align-->
          <ul class="nav navbar-nav navbar-right">
            <% unless logged_in? %>
              <li> <%= link_to t("nav_menu.sign_in" ), login_path %></li>
              <li> <%= link_to t("nav_menu.sign_up" ), new_user_path %></li>
            <% else %>
               <li> <%= link_to t("nav_menu.logout" ), logout_path, method: :delete %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row container-50 centered">
          <%= bootstrap_flash %>
          <%= yield %>
      </div><!--/row-->

      <footer>
      <%= debug(params) if Rails.env.development? %>

        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>